from db.models import competence
from db.models import language
from db.models import training
from db.models import position
from db.models import department
from db.models import experience
from db.models import worker_competence
from db.models import worker_training
from db.models import worker
from db.models import user