"""Training table institute

Revision ID: 0788b6ece50a
Revises: 3e4665958fca
Create Date: 2026-02-13 21:10:25.669368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0788b6ece50a'
down_revision: Union[str, Sequence[str], None] = '3e4665958fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Training', schema=None) as batch_op:
        batch_op.drop_column('institution')

    # ### end Alembic commands ###
