"""Experience table

Revision ID: 14cc4fcf943e
Revises: 789e76e932f8
Create Date: 2026-02-14 15:33:47.808184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cc4fcf943e'
down_revision: Union[str, Sequence[str], None] = '789e76e932f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('initial_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('wage', sa.Integer(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Experience_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Experience_id'))

    op.drop_table('Experience')
    # ### end Alembic commands ###
