"""Training table rename

Revision ID: 3e4665958fca
Revises: e9e8dc9f2792
Create Date: 2026-02-13 20:58:01.733243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4665958fca'
down_revision: Union[str, Sequence[str], None] = 'e9e8dc9f2792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('initial_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Training', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Training_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Training', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Training_id'))

    op.drop_table('Training')
    # ### end Alembic commands ###
