"""Add state

Revision ID: 6a5ed21bfc5f
Revises: 34e723d61ee5
Create Date: 2026-02-15 17:54:56.317596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5ed21bfc5f'
down_revision: Union[str, Sequence[str], None] = '34e723d61ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WorkerCompetence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=True))

    with op.batch_alter_table('WorkerTraining', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WorkerTraining', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('WorkerCompetence', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
