"""Worker table fix

Revision ID: 8bf1ebcc8000
Revises: d239e93bb410
Create Date: 2026-02-14 19:27:07.671846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf1ebcc8000'
down_revision: Union[str, Sequence[str], None] = 'd239e93bb410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_experience_worker_id_worker'), type_='foreignkey')
        batch_op.create_foreign_key('fk_experience_worker_id', 'Worker', ['worker_id'], ['id'])
        batch_op.drop_column('fk_experience_worker_id')

    with op.batch_alter_table('Worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recommended_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_worker_position_id_positions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_worker_department_id_department'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_worker_recommended_id_worker'), type_='foreignkey')
        batch_op.create_foreign_key('fk_worker_department_id', 'Department', ['department_id'], ['id'])
        batch_op.create_foreign_key('fk_worker_position_id', 'Positions', ['position_id'], ['id'])
        batch_op.create_foreign_key('fk_worker_recommended_id', 'Worker', ['recommended_id'], ['id'])
        batch_op.drop_column('fk_worker_recommended_id')
        batch_op.drop_column('fk_worker_position_id')
        batch_op.drop_column('fk_worker_department_id')

    with op.batch_alter_table('WorkerCompetence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('competence_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_workercompetence_worker_id_worker'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_workercompetence_competence_id_competence'), type_='foreignkey')
        batch_op.create_foreign_key('fk_workercompetence_worker_id', 'Worker', ['worker_id'], ['id'])
        batch_op.create_foreign_key('fk_workercompetence_competence_id', 'Competence', ['competence_id'], ['id'])
        batch_op.drop_column('fk_workercompetence_worker_id')
        batch_op.drop_column('fk_workercompetence_competence_id')

    with op.batch_alter_table('WorkerTraining', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('training_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_workertraining_worker_id_worker'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_workertraining_competence_id_training'), type_='foreignkey')
        batch_op.create_foreign_key('fk_workertraining_competence_id', 'Training', ['training_id'], ['id'])
        batch_op.create_foreign_key('fk_workertraining_worker_id', 'Worker', ['worker_id'], ['id'])
        batch_op.drop_column('fk_workertraining_competence_id')
        batch_op.drop_column('fk_workertraining_worker_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WorkerTraining', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_workertraining_worker_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fk_workertraining_competence_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_workertraining_worker_id', type_='foreignkey')
        batch_op.drop_constraint('fk_workertraining_competence_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_workertraining_competence_id_training'), 'Training', ['fk_workertraining_competence_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_workertraining_worker_id_worker'), 'Worker', ['fk_workertraining_worker_id'], ['id'])
        batch_op.drop_column('training_id')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('WorkerCompetence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_workercompetence_competence_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fk_workercompetence_worker_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_workercompetence_competence_id', type_='foreignkey')
        batch_op.drop_constraint('fk_workercompetence_worker_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_workercompetence_competence_id_competence'), 'Competence', ['fk_workercompetence_competence_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_workercompetence_worker_id_worker'), 'Worker', ['fk_workercompetence_worker_id'], ['id'])
        batch_op.drop_column('competence_id')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('Worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_worker_department_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fk_worker_position_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fk_worker_recommended_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_worker_recommended_id', type_='foreignkey')
        batch_op.drop_constraint('fk_worker_position_id', type_='foreignkey')
        batch_op.drop_constraint('fk_worker_department_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_worker_recommended_id_worker'), 'Worker', ['fk_worker_recommended_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_worker_department_id_department'), 'Department', ['fk_worker_department_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_worker_position_id_positions'), 'Positions', ['fk_worker_position_id'], ['id'])
        batch_op.drop_column('recommended_id')
        batch_op.drop_column('department_id')
        batch_op.drop_column('position_id')

    with op.batch_alter_table('Experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_experience_worker_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_experience_worker_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_experience_worker_id_worker'), 'Worker', ['fk_experience_worker_id'], ['id'])
        batch_op.drop_column('worker_id')

    # ### end Alembic commands ###
