"""Language table 2

Revision ID: 92ffad1a713f
Revises: 6fd4a7894d96
Create Date: 2026-02-13 00:02:14.194433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ffad1a713f'
down_revision: Union[str, Sequence[str], None] = '6fd4a7894d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Language_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Language_id'))

    op.drop_table('Language')
    # ### end Alembic commands ###
