"""Training table delete

Revision ID: e9e8dc9f2792
Revises: 418ddf40b35d
Create Date: 2026-02-13 20:57:37.931873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e8dc9f2792'
down_revision: Union[str, Sequence[str], None] = '418ddf40b35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_id'))

    op.drop_table('training')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('initial_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('state', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_id'), ['id'], unique=False)

    # ### end Alembic commands ###
